ansible_user: centos
ansible_password: DevOps321
#to encrypt the file use cmd
# ansible-vault encrypt group_vars/all.yaml
# naming convention all.yaml here all is considered for all hosts. If catalogue.yaml it will be considered for catlogue hosts

